/**
 * Référentiel initial complet des Types — CDC V2.0 Annexe A.
 *
 * ══════════════════════════════════════════════════════════════════════════
 * UN TYPE DÉCLARE SA RUBRIQUE, ET UNE SEULE
 *
 * Le §2.2 interdit les Types multi-rubriques, et le §15.1 en tire la
 * conséquence : les anciens Types génériques (`FACTURE`, `DEVIS`, `CONTRAT`)
 * sont scindés par finalité. C'est pourquoi on trouve ici quatre Types de
 * facture et non un seul — la Rubrique n'est plus déduite d'un contexte, elle
 * est portée par le Type lui-même.
 *
 * ── CHAQUE RUBRIQUE A SON PROPRE « AUTRE » ────────────────────────────────
 *
 * Le §2.2 l'impose : « Chaque Rubrique possède son propre code technique de
 * Type "Autre", même si le libellé visible reste "Autre", afin de respecter
 * 1 Type = 1 Rubrique. » Un `AUTRE` unique et partagé réintroduirait
 * exactement le type multi-rubriques que le CDC vient d'interdire.
 *
 * Tous portent `userOnly: true` (§5.2) : le prompt ne doit jamais les
 * proposer, et `isAiSelectable()` les écarte au niveau du référentiel plutôt
 * qu'au niveau du prompt — une consigne rédigée se contourne, un filtre non.
 * ══════════════════════════════════════════════════════════════════════════
 */
import type { DocumentTypeDefinition } from './types';

export const DOCUMENT_TYPES: readonly DocumentTypeDefinition[] = [
  // ── Propriété et gestion ────────────────────────────────────────────────
  {
    code: 'ACQUISITION_INVOICE',
    label: "Facture / justificatif d'acquisition",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: "Achat initial ou acquisition du bien.",
  },
  {
    code: 'ACQUISITION_ORDER',
    label: "Bon de commande d'acquisition",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: "Commande portant sur l'acquisition du bien.",
  },
  {
    code: 'ACQUISITION_DELIVERY',
    label: 'Bon de livraison / remise du bien',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Remise ou livraison du bien acquis.',
  },
  {
    code: 'ACQUISITION_PAYMENT',
    label: "Preuve de paiement d'acquisition",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: "Paiement directement lié à l'acquisition.",
  },
  {
    code: 'PROPERTY_TITLE',
    label: 'Acte / titre de propriété',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Preuve juridique de propriété.',
  },
  {
    code: 'TRANSACTION_ACT',
    label: 'Acte de transaction / cession',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Acte de vente, acquisition ou transfert.',
  },
  {
    code: 'TRANSFER_CERTIFICATE',
    label: 'Certificat de cession',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['VEHICULE', 'OBJECT', 'MATERIEL_PRO'],
    purpose: 'Transfert de propriété.',
  },
  {
    code: 'PROVENANCE_PROOF',
    label: 'Preuve de provenance',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['OBJECT', 'MATERIEL_PRO'],
    purpose: 'Origine et chaîne de provenance.',
  },
  {
    code: 'AUTHENTICITY_CERTIFICATE',
    label: "Certificat d'authenticité",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['OBJECT'],
    purpose: 'Authenticité / origine certifiée.',
  },
  {
    code: 'REGISTRATION_CERTIFICATE',
    label: "Certificat d'immatriculation",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['VEHICULE'],
    purpose: 'Identification administrative du véhicule.',
  },
  {
    code: 'ADMIN_STATUS_CERTIFICATE',
    label: 'Certificat de situation administrative',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['VEHICULE'],
    purpose: 'Situation administrative du véhicule.',
  },
  {
    code: 'CADASTRAL_PLAN',
    label: 'Plan cadastral',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Référence cadastrale du bien.',
  },
  {
    code: 'ASSET_REFERENCE_PLAN',
    label: 'Plan de référence du bien',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Plan existant / de référence, hors projet de travaux.',
  },
  {
    code: 'VALUE_ESTIMATE',
    label: 'Estimation / avis de valeur',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Valorisation du bien hors sinistre.',
  },
  {
    code: 'VALUE_APPRAISAL',
    label: 'Expertise de valeur hors sinistre',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Expertise dont la finalité est la valeur patrimoniale.',
  },
  {
    code: 'VALUED_INVENTORY',
    label: 'Inventaire valorisé',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Inventaire avec valorisation.',
  },
  {
    code: 'FINANCING_CONTRACT',
    label: 'Contrat de prêt / crédit lié au bien',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: "Financement de l'acquisition ou de la détention.",
  },
  {
    code: 'FINANCING_SCHEDULE',
    label: 'Échéancier de financement',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Échéancier du financement du bien.',
  },
  {
    code: 'FINANCING_GUARANTEE',
    label: 'Hypothèque / garantie de financement',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Sûreté attachée au financement.',
  },
  {
    code: 'LEASING_FINANCING_CONTRACT',
    label: 'Contrat de financement / leasing du bien',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['VEHICULE', 'MATERIEL_PRO'],
    purpose: 'LOA, LLD ou financement assimilé lié à la détention.',
  },
  {
    code: 'COPRO_RULES',
    label: 'Règlement de copropriété',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Règles de copropriété.',
  },
  {
    code: 'COPRO_AG_MINUTES',
    label: "Procès-verbal d'assemblée générale",
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Décisions de copropriété.',
  },
  {
    code: 'COPRO_CALL_FUNDS',
    label: 'Appel de fonds',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Appel de fonds de copropriété.',
  },
  {
    code: 'CHARGE_STATEMENT',
    label: 'Relevé de charges',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Charges liées à la détention.',
  },
  {
    code: 'PROPERTY_TAX_NOTICE',
    label: 'Avis de taxe / imposition liée au bien',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Taxe foncière ou imposition liée au bien.',
  },
  {
    code: 'CHARGE_RECEIPT',
    label: 'Quittance / justificatif de charge',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Paiement ou justificatif de charge.',
  },
  {
    code: 'OTHER_PROPERTY_MANAGEMENT',
    label: 'Autre',
    rubric: 'PROPERTY_MANAGEMENT',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Contrats, garanties et notices ──────────────────────────────────────
  {
    code: 'SERVICE_CONTRACT',
    label: 'Contrat de service',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: 'Service lié au bien sans transfert de propriété.',
  },
  {
    code: 'SUBSCRIPTION_CONTRACT',
    label: "Contrat d'abonnement",
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: "Abonnement lié au bien ou à son usage.",
  },
  {
    code: 'MAINTENANCE_CONTRACT',
    label: 'Contrat de maintenance',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: "Contrat encadrant l'entretien/maintenance.",
  },
  {
    code: 'WARRANTY_CERTIFICATE',
    label: 'Garantie',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: 'Garantie constructeur, vendeur ou prestataire.',
  },
  {
    code: 'EXTENDED_WARRANTY',
    label: 'Extension de garantie',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: 'Extension ou prolongation de garantie.',
  },
  {
    code: 'USER_MANUAL',
    label: 'Notice / manuel',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: "Notice d'utilisation.",
  },
  {
    code: 'TECHNICAL_SHEET',
    label: 'Fiche technique',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: 'Documentation technique du bien ou équipement.',
  },
  {
    code: 'SOFTWARE_LICENSE',
    label: 'Licence logicielle',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: ['MATERIEL_PRO', 'OBJECT'],
    purpose: 'Licence logicielle liée au bien.',
  },
  {
    code: 'OTHER_CONTRACTS_DOCS',
    label: 'Autre',
    rubric: 'CONTRACTS_WARRANTIES_DOCS',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Entretien et travaux ────────────────────────────────────────────────
  {
    code: 'MAINTENANCE_INVOICE',
    label: "Facture d'entretien",
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Entretien courant ou maintenance.',
  },
  {
    code: 'REPAIR_INVOICE',
    label: 'Facture de réparation',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Réparation ou remise en état.',
  },
  {
    code: 'WORKS_INVOICE',
    label: 'Facture de travaux',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Travaux ou modification durable.',
  },
  {
    code: 'MAINTENANCE_QUOTE',
    label: "Devis d'entretien",
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: "Devis d'entretien courant.",
  },
  {
    code: 'REPAIR_QUOTE',
    label: 'Devis de réparation',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Devis de réparation.',
  },
  {
    code: 'WORKS_QUOTE',
    label: 'Devis de travaux',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Devis de travaux / transformation.',
  },
  {
    code: 'MAINTENANCE_REPORT',
    label: "Rapport d'entretien",
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: "Compte rendu d'entretien.",
  },
  {
    code: 'INTERVENTION_REPORT',
    label: "Rapport d'intervention",
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Compte rendu d’intervention technique.',
  },
  {
    code: 'MAINTENANCE_LOG',
    label: "Carnet d'entretien",
    rubric: 'MAINTENANCE_WORKS',
    applicability: ['VEHICULE', 'MATERIEL_PRO'],
    purpose: "Historique d'entretien.",
  },
  {
    code: 'INSTALLATION_REPORT',
    label: "Rapport d'installation",
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: "Installation ou mise en service d'un équipement.",
  },
  {
    code: 'WORKS_PURCHASE_ORDER',
    label: 'Bon de commande de travaux',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Commande liée aux travaux.',
  },
  {
    code: 'WORKS_DELIVERY_NOTE',
    label: 'Bon de livraison de travaux / matériaux',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Livraison liée à un chantier.',
  },
  {
    code: 'WORKS_PAYMENT_PROOF',
    label: 'Preuve de paiement de travaux',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Paiement lié à des travaux.',
  },
  {
    code: 'WORKS_PLAN',
    label: 'Plan de travaux / aménagement',
    rubric: 'MAINTENANCE_WORKS',
    applicability: ['IMMOBILIER'],
    purpose: 'Plan lié à un projet de modification.',
  },
  {
    code: 'OTHER_MAINTENANCE_WORKS',
    label: 'Autre',
    rubric: 'MAINTENANCE_WORKS',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Assurances et sinistres ─────────────────────────────────────────────
  {
    code: 'INSURANCE_POLICY',
    label: "Contrat / police d'assurance",
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: "Couverture d'assurance du bien.",
  },
  {
    code: 'INSURANCE_CERTIFICATE',
    label: "Attestation d'assurance",
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Attestation de couverture.',
  },
  {
    code: 'INSURANCE_DUE_NOTICE',
    label: "Avis d'échéance d'assurance",
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Échéance / renouvellement / prime.',
  },
  {
    code: 'CLAIM_DECLARATION',
    label: 'Déclaration de sinistre',
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: "Ouverture d'un sinistre.",
  },
  {
    code: 'CLAIM_REPORT',
    label: 'Constat de sinistre',
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Constat ou déclaration circonstanciée.',
  },
  {
    code: 'CLAIM_APPRAISAL',
    label: "Rapport d'expertise de sinistre",
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Expertise réalisée dans le cadre d’un sinistre.',
  },
  {
    code: 'CLAIM_INDEMNITY',
    label: 'Décompte / indemnisation de sinistre',
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Proposition, décompte ou versement d’indemnisation.',
  },
  {
    code: 'CLAIM_CORRESPONDENCE',
    label: 'Courrier de gestion de sinistre',
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Échange formel relatif au sinistre.',
  },
  {
    code: 'OTHER_INSURANCE_CLAIMS',
    label: 'Autre',
    rubric: 'INSURANCE_CLAIMS',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Contrôles et conformité ─────────────────────────────────────────────
  {
    code: 'BUILDING_PERMIT',
    label: 'Permis de construire / autorisation réglementaire',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Autorisation réglementaire liée au bien ou aux travaux.',
  },
  {
    code: 'CARREZ_CERTIFICATE',
    label: 'Certificat loi Carrez',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Mesurage légal.',
  },
  {
    code: 'DPE',
    label: 'DPE',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic de performance énergétique.',
  },
  {
    code: 'ENERGY_AUDIT',
    label: 'Audit énergétique',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Audit énergétique.',
  },
  {
    code: 'ASBESTOS_DIAGNOSTIC',
    label: 'Diagnostic amiante',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic amiante.',
  },
  {
    code: 'LEAD_DIAGNOSTIC',
    label: 'Diagnostic plomb (CREP)',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic plomb.',
  },
  {
    code: 'TERMITE_DIAGNOSTIC',
    label: 'Diagnostic termites',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic termites.',
  },
  {
    code: 'GAS_DIAGNOSTIC',
    label: 'Diagnostic gaz',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic gaz.',
  },
  {
    code: 'ELECTRICITY_DIAGNOSTIC',
    label: 'Diagnostic électricité',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic électrique.',
  },
  {
    code: 'SANITATION_DIAGNOSTIC',
    label: 'Diagnostic assainissement',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Diagnostic assainissement.',
  },
  {
    code: 'RISK_STATEMENT',
    label: 'État des risques',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'ERNMT/ERP ou équivalent.',
  },
  {
    code: 'RE2020_CERTIFICATE',
    label: 'Attestation RE2020',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Conformité énergétique/réglementaire.',
  },
  {
    code: 'BUILDING_LABEL_CERTIFICATE',
    label: 'Label / certification bâtiment',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['IMMOBILIER'],
    purpose: 'Certification ou label du bâtiment.',
  },
  {
    code: 'VEHICLE_TECHNICAL_INSPECTION',
    label: 'Contrôle technique',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['VEHICULE'],
    purpose: 'Contrôle réglementaire du véhicule.',
  },
  {
    code: 'CE_DECLARATION',
    label: 'Déclaration de conformité CE',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['MATERIEL_PRO', 'OBJECT'],
    purpose: 'Conformité CE.',
  },
  {
    code: 'CALIBRATION_CERTIFICATE',
    label: "Certificat d'étalonnage",
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['MATERIEL_PRO'],
    purpose: 'Étalonnage / métrologie.',
  },
  {
    code: 'SAFETY_CONTROL_REPORT',
    label: 'Rapport de contrôle de sécurité',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: ['MATERIEL_PRO', 'IMMOBILIER'],
    purpose: 'Contrôle sécurité.',
  },
  {
    code: 'GENERAL_TECHNICAL_DIAGNOSTIC',
    label: 'Diagnostic technique',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: 'ALL',
    purpose: 'Diagnostic non couvert par un type plus précis.',
  },
  {
    code: 'COMPLIANCE_CERTIFICATE',
    label: 'Attestation / certificat de conformité',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: 'ALL',
    purpose: 'Conformité non couverte par un type plus précis.',
  },
  {
    code: 'OTHER_COMPLIANCE_CONTROLS',
    label: 'Autre',
    rubric: 'COMPLIANCE_CONTROLS',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Photos et vidéos ────────────────────────────────────────────────────
  {
    code: 'PHOTO',
    label: 'Photo',
    rubric: 'MEDIA',
    applicability: 'ALL',
    purpose: 'La photo constitue le contenu documentaire.',
  },
  {
    code: 'VIDEO',
    label: 'Vidéo',
    rubric: 'MEDIA',
    applicability: 'ALL',
    purpose: 'La vidéo constitue le contenu documentaire.',
  },
  {
    code: 'OTHER_MEDIA',
    label: 'Autre',
    rubric: 'MEDIA',
    applicability: 'ALL',
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Gestion locative ────────────────────────────────────────────────────
  {
    code: 'RENTAL_LEASE',
    label: 'Bail de location',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Bail relatif à la location du bien.',
  },
  {
    code: 'RENTAL_LEASE_AMENDMENT',
    label: 'Avenant au bail',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Modification du bail.',
  },
  {
    code: 'MOVE_IN_REPORT',
    label: "État des lieux d'entrée",
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'État des lieux entrant.',
  },
  {
    code: 'MOVE_OUT_REPORT',
    label: 'État des lieux de sortie',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'État des lieux sortant.',
  },
  {
    code: 'RENT_RECEIPT',
    label: 'Quittance de loyer',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Quittance liée à la location.',
  },
  {
    code: 'SECURITY_DEPOSIT_RECEIPT',
    label: 'Dépôt de garantie',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Justificatif de dépôt ou restitution.',
  },
  {
    code: 'RENTAL_CHARGE_ADJUSTMENT',
    label: 'Régularisation de charges locatives',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Régularisation des charges du locataire.',
  },
  {
    code: 'RENTAL_MANAGEMENT_STATEMENT',
    label: 'Relevé de gestion locative',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Compte rendu / relevé de gestion locative.',
  },
  {
    code: 'RENTAL_CORRESPONDENCE',
    label: 'Courrier de gestion locative',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Échange formel avec le locataire ou gestionnaire.',
  },
  {
    code: 'OTHER_RENTAL',
    label: 'Autre',
    rubric: 'RENTAL_MANAGEMENT',
    applicability: ['IMMOBILIER'],
    purpose: 'Choix utilisateur uniquement.',
    userOnly: true,
  },

  // ── Autres documents ────────────────────────────────────────────────────
  {
    code: 'OTHER_DOCUMENT',
    label: 'Autre',
    rubric: 'OTHER_DOCUMENTS',
    applicability: 'ALL',
    purpose: 'Dernier recours ; choix utilisateur uniquement.',
    userOnly: true,
  },
] as const;
