# Vérifie que tous les fichiers livrés sont présents dans le dépôt.
# Usage, depuis la racine de verebona-app :
#     powershell -ExecutionPolicy Bypass -File .\verifier-fichiers.ps1

$fichiers = @(
  # ── Correctif inscription ────────────────────────────────────────────────
  'middleware.ts',
  'src/app/(auth)/signup/page.tsx',
  'src/app/(auth)/verify-email/page.tsx',
  'src/app/abonnement/onboarding/page.tsx',
  'src/app/api/auth/verify-email/route.ts',
  'src/app/api/health/route.ts',
  'src/app/api/users/route.ts',
  'src/db/index.ts',
  'src/db/migrations/0112_users_schema_alignment.sql',
  'src/db/migrations/0113_signup_context_account_link.sql',
  'src/services/referral-attribution.service.ts',
  'src/services/__tests__/referral-attribution.test.ts',
  # ── L0-bis tarification ──────────────────────────────────────────────────
  'src/db/migrations/0114_pricing_public_catalog_source.sql',
  'src/services/ai/gateway/pricing/gemini-public-catalog.ts',
  'src/services/ai/gateway/pricing/gemini-public.source.ts',
  'src/services/ai/gateway/pricing/__tests__/gemini-public-catalog.test.ts',
  # ── Lot 0 ────────────────────────────────────────────────────────────────
  'src/app/api/cron/ai/purge-assistant-logs/route.ts',
  'src/services/ai/source-analysis/__tests__/web-link-entrypoint.test.ts',
  # ── Lots 1 à 3 : CGVU ────────────────────────────────────────────────────
  'src/db/migrations/0115_legal_document_versions.sql',
  'src/db/seeds/legal/cgvu-v1.content.ts',
  'src/db/seeds/legal/seed-cgvu.ts',
  'src/db/seeds/legal/email_template_cgvu.ts',
  'src/lib/load-env.ts',
  'scripts/verify-legal-integrity.ts',
  'src/services/legal/index.ts',
  'src/services/legal/legal-versions.service.ts',
  'src/services/legal/legal-html.renderer.ts',
  'src/services/legal/legal-audit.service.ts',
  'src/services/legal/legal-storage.ts',
  'src/services/legal/legal-acceptances.service.ts',
  'src/services/legal/legal-error-page.ts',
  'src/services/legal/legal-confirmation.service.ts',
  'src/services/legal/legal-subscription.hook.ts',
  'src/services/legal/__tests__/legal-html.test.ts',
  'src/services/legal/__tests__/legal-seed-content.test.ts',
  'src/services/legal/__tests__/legal-acceptances.test.ts',
  'src/services/legal/__tests__/legal-confirmation.test.ts',
  'src/app/cgvu/route.ts',
  'src/app/cgvu/versions/[version]/route.ts',
  'src/app/api/legal/cgvu/current/route.ts',
  'src/app/api/legal/cgvu/versions/[version]/route.ts',
  'src/app/api/legal/cgvu/versions/[version]/download/route.ts',
  'src/app/api/legal/acceptances/route.ts',
  'src/app/api/me/legal/acceptances/route.ts',
  'src/app/api/me/legal/cgvu-applicable/route.ts',
  'src/components/account/LegalInformationCard.tsx',
  'src/app/admin/cgvu/page.tsx',
  'src/app/api/admin/legal/cgvu/drafts/route.ts',
  'src/app/api/admin/legal/cgvu/drafts/[id]/route.ts',
  'src/app/api/admin/legal/cgvu/drafts/[id]/publish/route.ts',
  'src/app/api/admin/legal/cgvu/versions/route.ts',
  'src/app/api/admin/legal/cgvu/versions/[id]/set-current/route.ts',
  'src/app/api/cron/legal/verify-integrity/route.ts',
  # ── Lot A3 ───────────────────────────────────────────────────────────────
  'src/db/migrations/0116_scheduled_account_deletions.sql',
  'src/services/legal/french-calendar.ts',
  'src/services/legal/__tests__/french-calendar.test.ts',
  'src/services/account/scheduled-deletion.service.ts',
  'src/services/account/__tests__/scheduled-deletion.test.ts',
  'src/app/api/cron/account-deletion/process/route.ts',
  # ── Lots A2a à A2d : rétractation ────────────────────────────────────────
  'src/db/migrations/0117_withdrawal_requests.sql',
  'src/db/migrations/0118_withdrawal_events.sql',
  'src/db/seeds/withdrawal/email_template_withdrawal.ts',
  'src/services/withdrawal/eligibility.service.ts',
  'src/services/withdrawal/withdrawal.service.ts',
  'src/services/withdrawal/summary.service.ts',
  'src/services/withdrawal/public-verification.service.ts',
  'src/services/withdrawal/receipt.service.ts',
  'src/services/withdrawal/refund-calculator.ts',
  'src/services/withdrawal/withdrawal-processor.service.ts',
  'src/services/withdrawal/withdrawal-webhook.service.ts',
  'src/services/withdrawal/withdrawal-journal.service.ts',
  'src/services/withdrawal/__tests__/withdrawal.test.ts',
  'src/services/withdrawal/__tests__/withdrawal-ui.test.ts',
  'src/services/withdrawal/__tests__/refund-calculator.test.ts',
  'src/services/withdrawal/__tests__/withdrawal-journal.test.ts',
  'src/app/retractation/page.tsx',
  'src/app/api/withdrawal/eligibility/route.ts',
  'src/app/api/withdrawal/prepare/route.ts',
  'src/app/api/withdrawal/confirm/route.ts',
  'src/app/api/withdrawal/public/start/route.ts',
  'src/app/api/withdrawal/public/verify/route.ts',
  'src/app/api/withdrawal/[reference]/route.ts',
  'src/app/api/cron/withdrawal/process/route.ts',
  'src/components/account/WithdrawalCard.tsx',
  'src/app/admin/retractations/page.tsx',
  'src/app/api/admin/withdrawals/route.ts',
  'src/app/api/admin/withdrawals/[reference]/route.ts',
  'src/app/api/admin/withdrawals/[reference]/actions/route.ts',
  # ── Lot C1a : classement ─────────────────────────────────────────────────
  'src/db/migrations/0119_document_categories.sql',
  'src/db/seeds/documents/category-referential.ts',
  'src/db/seeds/documents/seed-document-categories.ts',
  'src/services/documents/classification-rules.ts',
  'src/services/documents/__tests__/classification-rules.test.ts',
  'src/app/api/admin/document-categories/route.ts',
  'src/app/api/admin/document-categories/[id]/route.ts',
  'src/services/documents/document-query.contract.ts',
  'src/services/documents/document-query.service.ts',
  'src/services/documents/classification.service.ts',
  'src/services/documents/__tests__/document-query.test.ts',
  'src/app/api/documents/browse/route.ts',
  'src/app/api/documents/[id]/classification/route.ts',
  'src/components/documents/DocumentCard.tsx',
  'src/components/documents/CategoryAccordion.tsx',
  'src/components/documents/SortFilterDrawer.tsx',
  'src/components/documents/DocumentClassificationSection.tsx',
  'src/components/documents/useDocumentBrowser.ts',
  'src/components/documents/DocumentsView.tsx',
  'src/components/documents/__tests__/document-components.test.ts',
  'scripts/corpus-status.ts',
  'src/services/ai/governance/corpus/corpus-cases.ts',
  'src/services/ai/governance/corpus/__tests__/corpus-cases.test.ts',
  'src/services/ai/governance/corpus/fixtures/acte_immobilier/acte-vente-appartement.html',
  'src/services/ai/governance/corpus/fixtures/acte_immobilier/acte-vente-maison.html',
  'src/services/ai/governance/corpus/fixtures/acte_immobilier/compromis-vente-terrain.html',
  'src/services/ai/governance/corpus/fixtures/avis_echeance/avis-echeance-auto.html',
  'src/services/ai/governance/corpus/fixtures/avis_echeance/avis-echeance-habitation.html',
  'src/services/ai/governance/corpus/fixtures/carte_grise/certificat-immatriculation-moto.html',
  'src/services/ai/governance/corpus/fixtures/carte_grise/certificat-immatriculation-voiture.html',
  'src/services/ai/governance/corpus/fixtures/contrat_loa_lld/contrat-lld-utilitaire.html',
  'src/services/ai/governance/corpus/fixtures/contrat_loa_lld/contrat-loa-voiture.html',
  'src/services/ai/governance/corpus/fixtures/document_contradictoire/annonce-immobiliere-surface.html',
  'src/services/ai/governance/corpus/fixtures/document_contradictoire/avis-echeance-prime-differente.html',
  'src/services/ai/governance/corpus/fixtures/document_sans_information/page-separation-vierge.html',
  'src/services/ai/governance/corpus/fixtures/document_sans_information/ticket-illisible.html',
  'src/services/ai/governance/corpus/fixtures/dpe/dpe-appartement-bordeaux.html',
  'src/services/ai/governance/corpus/fixtures/dpe/dpe-maison-fleury.html',
  'src/services/ai/governance/corpus/fixtures/facture_equipement/facture-ordinateur-pro.html',
  'src/services/ai/governance/corpus/fixtures/facture_equipement/facture-pompe-chaleur.html',
  'src/services/ai/governance/corpus/fixtures/facture_multibiens/facture-assurance-deux-biens.html',
  'src/services/ai/governance/corpus/fixtures/facture_multibiens/facture-travaux-deux-lots.html',
  'src/services/ai/governance/corpus/fixtures/garantie/certificat-garantie-electromenager.html',
  'src/services/ai/governance/corpus/fixtures/garantie/extension-garantie-pompe-chaleur.html',
  'src/services/ai/governance/corpus/fixtures/multi_fichiers_meme_document/dpe-bordeaux-page1.html',
  'src/services/ai/governance/corpus/fixtures/multi_fichiers_meme_document/dpe-bordeaux-page2.html',
  'src/services/ai/governance/corpus/fixtures/multi_fichiers_meme_document/dpe-bordeaux-page3.html',
  'src/services/ai/governance/corpus/fixtures/page_web/annonce-portail-immobilier.html',
  'src/services/ai/governance/corpus/fixtures/page_web/fiche-produit-fabricant.html',
  'src/services/ai/governance/corpus/fixtures/rapport_entretien/rapport-entretien-chaudiere.html',
  'src/services/ai/governance/corpus/fixtures/rapport_entretien/rapport-revision-voiture.html',
  'scripts/corpus-run.ts',
  'scripts/corpus-dry.ts',
  'src/services/ai/governance/corpus/corpus-comparator.ts',
  'src/services/ai/governance/corpus/corpus-runner.ts',
  'src/services/ai/governance/corpus/analysis-runner.ts',
  'src/services/ai/governance/corpus/__tests__/corpus-comparator.test.ts',
  'src/db/seeds/corpus/seed-corpus-account.ts',
  'src/scripts/migrate-auth-storage.ts',
  'src/lib/__tests__/no-bearer-token.test.ts'
)

$manquants = @()
foreach ($f in $fichiers) {
  if (-not (Test-Path -LiteralPath $f)) { $manquants += $f }
}

Write-Host ""
Write-Host "$($fichiers.Count) fichier(s) attendu(s)."
if ($manquants.Count -eq 0) {
  Write-Host "OK - tous les fichiers sont presents." -ForegroundColor Green
  exit 0
} else {
  Write-Host "$($manquants.Count) fichier(s) MANQUANT(S) :" -ForegroundColor Red
  $manquants | ForEach-Object { Write-Host "   $_" -ForegroundColor Red }
  exit 1
}
