-- Migration 0218 (index 1/2) : document_facts (compte, clé canonique) — CDC 15 T1-01.
-- UNE instruction par fichier : `CREATE INDEX CONCURRENTLY` ne peut pas
-- s'exécuter dans une transaction, et une requête à instruction unique n'en
-- ouvre pas (`ensureMigrations` passe le fichier tel quel). Aucun verrou
-- bloquant les écritures de faits pendant la construction.
-- Idempotente (IF NOT EXISTS). Si une construction est interrompue, l'index
-- reste INVALIDE et IF NOT EXISTS ne le reconstruit pas : le supprimer
-- (DROP INDEX CONCURRENTLY <nom>) puis redémarrer — contrôle :
--   SELECT indexrelid::regclass FROM pg_index WHERE NOT indisvalid;
-- Index partiel : les faits génériques et antérieurs n'ont pas de clé canonique.
CREATE INDEX CONCURRENTLY IF NOT EXISTS document_facts_account_canonical_idx ON document_facts (account_id, canonical_key) WHERE canonical_key IS NOT NULL AND status = 'active';
