-- Migration 0241 (index 1/1) : unicité de l'identifiant d'opération de dépôt
-- par utilisateur (APP-PERF-30). Deux `presign` simultanés avec la même clé
-- ne peuvent pas créer deux lignes : le second échoue (23505) et relit la
-- ligne du premier. Partiel : les lignes sans clé (existantes, vignettes,
-- anciens clients) n'entrent pas dans l'index.
-- UNE instruction par fichier : `CREATE INDEX CONCURRENTLY` ne peut pas
-- s'exécuter dans une transaction ; aucun verrou bloquant les dépôts pendant
-- la construction. Idempotente ; un index laissé INVALIDE est reconstruit au
-- démarrage (`migration-index.ts`).
--
-- INDEX OPTIONNEL (lot 24b) — bien qu'UNIQUE, il n'est qu'un filet :
-- l'unicité « une opération = une ligne » est garantie par le code, sous
-- verrou consultatif transactionnel (`uploadOperationLockKey`) avec relecture
-- avant insertion (`/api/files/presign`) et avant d'attacher la clé
-- (`/api/files/confirm`). Aucune requête n'en dépend (pas d'ON CONFLICT sur
-- ces colonnes ; le 23505 éventuel est traité comme une reprise). Son absence
-- (construction différée au déploiement) ne crée ni doublon ni erreur 500 ;
-- il est construit plus tard en arrière-plan.
-- verebona:optional-index
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS asset_files_user_upload_operation_uidx ON asset_files (user_id, upload_operation_id) WHERE upload_operation_id IS NOT NULL;
