export const NOTIFICATION_TYPES = {
  DUO_MOVE_REQUEST: 'DUO_MOVE_REQUEST',
  DUO_DELETE_REQUEST: 'DUO_DELETE_REQUEST',
  DUO_MOVE_ACCEPTED: 'DUO_MOVE_ACCEPTED',
  DUO_MOVE_REFUSED: 'DUO_MOVE_REFUSED',
  DUO_DELETE_ACCEPTED: 'DUO_DELETE_ACCEPTED',
  DUO_DELETE_REFUSED: 'DUO_DELETE_REFUSED',
  ACCOUNT_INVITATION: 'ACCOUNT_INVITATION',
  DOCUMENT_ANALYZED: 'DOCUMENT_ANALYZED',
  TRANSMISSION_RECEIVED: 'TRANSMISSION_RECEIVED',
  TRANSMISSION_ACCEPTED: 'TRANSMISSION_ACCEPTED',
  TRANSMISSION_REFUSED: 'TRANSMISSION_REFUSED',
  REFERRAL_REWARD_GRANTED: 'REFERRAL_REWARD_GRANTED',
} as const;

export type NotificationType = typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES];
