import { db } from '@/db';
import { deadlines } from '@/db/schema';

async function main() {
    const sampleDeadlines = [
        {
            userId: 1,
            accountId: 1,
            assetId: 2,
            label: 'Contrôle technique 2025',
            deadlineDate: '2025-03-15',
            deadlineType: 'OBLIGATOIRE',
            isDone: false,
            doneDate: null,
            notes: 'Tous les 2 ans',
            createdAt: new Date('2024-12-05'),
        },
        {
            userId: 1,
            accountId: 1,
            assetId: 1,
            label: 'Entretien chaudière annuel',
            deadlineDate: '2025-09-10',
            deadlineType: 'OBLIGATOIRE',
            isDone: false,
            doneDate: null,
            notes: 'Obligatoire chaque année',
            createdAt: new Date('2024-12-08'),
        },
        {
            userId: 2,
            accountId: 1,
            assetId: 4,
            label: 'Ramonage cheminée',
            deadlineDate: '2025-10-01',
            deadlineType: 'OBLIGATOIRE',
            isDone: false,
            doneDate: null,
            notes: 'Avant période de chauffe',
            createdAt: new Date('2024-12-10'),
        },
        {
            userId: 2,
            accountId: 1,
            assetId: 4,
            label: 'Vérification toiture',
            deadlineDate: '2025-04-15',
            deadlineType: 'RECOMMANDE',
            isDone: false,
            doneDate: null,
            notes: 'Après hiver',
            createdAt: new Date('2024-12-12'),
        },
        {
            userId: 3,
            accountId: 1,
            assetId: 5,
            label: 'Révision utilitaire',
            deadlineDate: '2025-06-15',
            deadlineType: 'OBLIGATOIRE',
            isDone: false,
            doneDate: null,
            notes: 'Tous les ans ou 20000 km',
            createdAt: new Date('2024-12-15'),
        },
        {
            userId: 3,
            accountId: 1,
            assetId: 3,
            label: 'Renouvellement assurance matériel',
            deadlineDate: '2025-01-20',
            deadlineType: 'RECOMMANDE',
            isDone: false,
            doneDate: null,
            notes: 'AppleCare expire',
            createdAt: new Date('2024-12-18'),
        },
        {
            userId: 5,
            accountId: 1,
            assetId: 7,
            label: 'Vente véhicule',
            deadlineDate: '2025-02-28',
            deadlineType: 'PERSO',
            isDone: false,
            doneDate: null,
            notes: 'Objectif vente avant mars',
            createdAt: new Date('2024-12-20'),
        },
        {
            userId: 1,
            accountId: 1,
            assetId: 2,
            label: 'Vidange moteur',
            deadlineDate: '2025-08-20',
            deadlineType: 'RECOMMANDE',
            isDone: false,
            doneDate: null,
            notes: 'Tous les 15000 km',
            createdAt: new Date('2024-12-22'),
        },
        {
            userId: 1,
            accountId: 1,
            assetId: 1,
            label: 'Ravalement façade copropriété',
            deadlineDate: '2026-06-01',
            deadlineType: 'OBLIGATOIRE',
            isDone: false,
            doneDate: null,
            notes: 'Vote AG prévu',
            createdAt: new Date('2024-12-23'),
        },
        {
            userId: 3,
            accountId: 1,
            assetId: 6,
            label: 'Vérification outillage professionnel',
            deadlineDate: '2025-01-15',
            deadlineType: 'PERSO',
            isDone: false,
            doneDate: null,
            notes: 'Inventaire annuel début année',
            createdAt: new Date('2024-12-25'),
        }
    ];

    await db.insert(deadlines).values(sampleDeadlines);
    
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});