import { db } from '@/db';
import { documents } from '@/db/schema';

async function main() {
    const sampleDocuments = [
        {
            userId: 1,
            assetId: 1,
            documentType: 'CONTRAT',
            fileName: 'acte_vente_appartement_lyon.pdf',
            fileUrl: '/uploads/documents/acte_vente_appartement_lyon.pdf',
            mimeType: 'application/pdf',
            fileSize: 2458000,
            documentDate: '2018-05-15',
            description: 'Acte de vente notarié',
            createdAt: new Date('2024-12-01T10:30:00'),
        },
        {
            userId: 1,
            assetId: 1,
            documentType: 'DIAGNOSTIC',
            fileName: 'dpe_appartement_lyon.pdf',
            fileUrl: '/uploads/documents/dpe_appartement_lyon.pdf',
            mimeType: 'application/pdf',
            fileSize: 850000,
            documentDate: '2018-04-20',
            description: 'Diagnostic de performance énergétique',
            createdAt: new Date('2024-12-02T14:15:00'),
        },
        {
            userId: 1,
            assetId: 2,
            documentType: 'FACTURE',
            fileName: 'facture_achat_peugeot_208.pdf',
            fileUrl: '/uploads/documents/facture_achat_peugeot_208.pdf',
            mimeType: 'application/pdf',
            fileSize: 320000,
            documentDate: '2020-03-10',
            description: 'Facture d\'achat véhicule',
            createdAt: new Date('2024-12-03T09:20:00'),
        },
        {
            userId: 1,
            assetId: 2,
            documentType: 'GARANTIE',
            fileName: 'garantie_peugeot_208.pdf',
            fileUrl: '/uploads/documents/garantie_peugeot_208.pdf',
            mimeType: 'application/pdf',
            fileSize: 180000,
            documentDate: '2020-03-10',
            description: 'Certificat de garantie 2 ans',
            createdAt: new Date('2024-12-04T11:45:00'),
        },
        {
            userId: 3,
            assetId: 3,
            documentType: 'FACTURE',
            fileName: 'facture_macbook_pro.pdf',
            fileUrl: '/uploads/documents/facture_macbook_pro.pdf',
            mimeType: 'application/pdf',
            fileSize: 215000,
            documentDate: '2023-01-20',
            description: 'Facture Apple Store',
            createdAt: new Date('2024-12-05T16:30:00'),
        },
        {
            userId: 2,
            assetId: 4,
            documentType: 'CONTRAT',
            fileName: 'acte_vente_maison_bordeaux.pdf',
            fileUrl: '/uploads/documents/acte_vente_maison_bordeaux.pdf',
            mimeType: 'application/pdf',
            fileSize: 3200000,
            documentDate: '2015-09-01',
            description: 'Acte de vente notarié maison',
            createdAt: new Date('2024-12-06T08:00:00'),
        },
        {
            userId: 2,
            assetId: 4,
            documentType: 'PHOTO_ETAT',
            fileName: 'photos_maison_bordeaux.zip',
            fileUrl: '/uploads/documents/photos_maison_bordeaux.zip',
            mimeType: 'application/zip',
            fileSize: 15800000,
            documentDate: '2015-08-25',
            description: 'Photos état des lieux achat',
            createdAt: new Date('2024-12-07T13:25:00'),
        },
        {
            userId: 3,
            assetId: 5,
            documentType: 'FACTURE',
            fileName: 'facture_renault_master.pdf',
            fileUrl: '/uploads/documents/facture_renault_master.pdf',
            mimeType: 'application/pdf',
            fileSize: 420000,
            documentDate: '2021-06-15',
            description: 'Facture achat utilitaire',
            createdAt: new Date('2024-12-08T10:10:00'),
        },
        {
            userId: 3,
            assetId: 6,
            documentType: 'FACTURE',
            fileName: 'facture_outillage_pro.pdf',
            fileUrl: '/uploads/documents/facture_outillage_pro.pdf',
            mimeType: 'application/pdf',
            fileSize: 280000,
            documentDate: '2021-07-01',
            description: 'Facture kit outillage complet',
            createdAt: new Date('2024-12-09T15:40:00'),
        },
        {
            userId: 5,
            assetId: 7,
            documentType: 'AUTRE',
            fileName: 'annonce_vente_megane.pdf',
            fileUrl: '/uploads/documents/annonce_vente_megane.pdf',
            mimeType: 'application/pdf',
            fileSize: 95000,
            documentDate: '2024-11-01',
            description: 'Annonce pour revente véhicule',
            createdAt: new Date('2024-12-10T12:05:00'),
        },
    ];

    await db.insert(documents).values(sampleDocuments);
    
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});