import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const sampleEvents = [
        {
            accountId: 1,
            userId: 1,
            assetId: 1,
            categorie: 'TRAVAUX',
            title: 'Rénovation salle de bain',
            date: '2022-09-15',
            provider: 'Artisan Réno Plus',
            costCents: 850000,
            notes: 'Nouvelle douche italienne et carrelage',
            createdAt: new Date('2024-12-01'),
        },
        {
            accountId: 1,
            userId: 1,
            assetId: 2,
            categorie: 'ENTRETIEN',
            title: 'Révision 40000 km',
            date: '2023-08-20',
            provider: 'Garage Peugeot Lyon',
            costCents: 28500,
            notes: 'Vidange et filtres',
            createdAt: new Date('2024-12-02'),
        },
        {
            accountId: 1,
            userId: 1,
            assetId: 2,
            categorie: 'CONTROLE',
            title: 'Contrôle technique',
            date: '2024-03-15',
            provider: 'Dekra Lyon 3',
            costCents: 7800,
            notes: 'Contrôle OK, contre-visite non nécessaire',
            createdAt: new Date('2024-12-03'),
        },
        {
            accountId: 1,
            userId: 2,
            assetId: 4,
            categorie: 'ENTRETIEN',
            title: 'Ramonage cheminée',
            date: '2024-10-05',
            provider: 'Ramonage du Sud-Ouest',
            costCents: 9500,
            notes: 'Certificat fourni',
            createdAt: new Date('2024-12-04'),
        },
        {
            accountId: 1,
            userId: 2,
            assetId: 4,
            categorie: 'TRAVAUX',
            title: 'Isolation combles',
            date: '2023-11-20',
            provider: 'Iso Habitat Bordeaux',
            costCents: 620000,
            notes: 'Laine de roche 300mm',
            createdAt: new Date('2024-12-05'),
        },
        {
            accountId: 1,
            userId: 3,
            assetId: 5,
            categorie: 'ENTRETIEN',
            title: 'Révision annuelle utilitaire',
            date: '2024-06-10',
            provider: 'Renault Pro Garage',
            costCents: 42000,
            notes: 'Révision complète + courroie distribution',
            createdAt: new Date('2024-12-06'),
        },
        {
            accountId: 1,
            userId: 3,
            assetId: 5,
            categorie: 'REPARATION',
            title: 'Remplacement embrayage',
            date: '2023-03-25',
            provider: 'Renault Pro Garage',
            costCents: 115000,
            notes: 'Embrayage usé à 85000 km',
            createdAt: new Date('2024-12-07'),
        },
        {
            accountId: 1,
            userId: 5,
            assetId: 7,
            categorie: 'REPARATION',
            title: 'Changement batterie',
            date: '2024-01-15',
            provider: 'Garage Renault',
            costCents: 18500,
            notes: "Batterie d'origine HS après 4 ans",
            createdAt: new Date('2024-12-08'),
        },
        {
            accountId: 1,
            userId: 1,
            assetId: 1,
            categorie: 'ENTRETIEN',
            title: 'Entretien chaudière gaz',
            date: '2024-09-10',
            provider: 'GazService Lyon',
            costCents: 12000,
            notes: 'Entretien annuel obligatoire',
            createdAt: new Date('2024-12-09'),
        },
        {
            accountId: 1,
            userId: 3,
            assetId: 6,
            categorie: 'REPARATION',
            title: 'Réparation poste à souder',
            date: '2024-05-18',
            provider: 'Matériel Pro Services',
            costCents: 28000,
            notes: 'Remplacement carte électronique',
            createdAt: new Date('2024-12-10'),
        },
    ];

    await db.insert(events).values(sampleEvents);
    
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
